sudo: required
language: generic

services:
  - docker

# build test images
before_install:
  # - docker build -t $DOCKER_HUB_USER/react-test -f ./client/Dockerfile.dev ./client
#   - docker build -t $DOCKER_HUB_USER/node-test -f ./server/Dockerfile.dev ./server

# run test images
script:
  - if [ $TRAVIS_PULL_REQUEST == "false" ]; then
    echo "not a pull request script";
    fi

    # - docker run -e CI=true $DOCKER_HUB_USER/react-test npm run test -- --coverage
    # - env | grep 'TRAVIS_NODE_' | sed -r 's/^TRAVIS_NODE_//' > env.list
    # - docker run --env-file <(bash -c "env | grep 'TRAVIS_NODE_' | sed -r 's/^TRAVIS_NODE_//'") -e CI=true $DOCKER_HUB_USER/node-test npm run test -- --coverage
    # - docker run --env-file env.list -e CI=true $DOCKER_HUB_USER/node-test npm run test -- --coverage
    # - rm env.list

after_success:
#   # creating images
#   - docker build -t $DOCKER_HUB_USER/fcfs-client ./client
#   - docker build -t $DOCKER_HUB_USER/fcfs-nginx ./nginx
#   - docker build -t $DOCKER_HUB_USER/fcfs-server ./server
#   # Log in to the docker CLI
#   - echo "$DOCKER_PSWRD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
#   # pushing images to docker hub
#   - docker push $DOCKER_HUB_USER/fcfs-client
#   - docker push $DOCKER_HUB_USER/fcfs-nginx
#   - docker push $DOCKER_HUB_USER/fcfs-server

deploy:
  on:
    branch: main
  - if [ $TRAVIS_PULL_REQUEST == "false" ]; then
    echo "not a pull request deploy";
    fi
#   provider: elasticbeanstalk
#   region: 'us-east-1'
#   app: 'fcfs'
#   env: 'Fcfs-env'
#   bucket_name: 'fcfs-us-east-1'
#   bucket_path: 'fcfs-multi-docker'
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY

notifications:
  email:
    on_success: never
    on_failure: always
