sudo: required
language: generic

services:
  - docker

before_install:
  # create env file & filter out PATH and DOCKER docker run --env-file .env
  - env | grep -vE "^(PATH=)" > .env
  # creating images
  - docker build -t $DOCKER_HUB_USER/fcfs-client ./client
  - docker build -t $DOCKER_HUB_USER/fcfs-nginx ./nginx
  - docker build -t $DOCKER_HUB_USER/fcfs-server ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PSWRD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
  # pushing images to docker hub
  - docker push $DOCKER_HUB_USER/fcfs-client
  - docker push $DOCKER_HUB_USER/fcfs-nginx
  - docker push $DOCKER_HUB_USER/fcfs-server
