version: '3'

services:
  fcfs-api:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: fcfs_api_nginx
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 5000:5000
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: ${MONGO_URI}
      GEOCODER_PROVIDER: ${GEOCODER_PROVIDER}
      GEO_PROVIDER_API_KEY: ${GEO_PROVIDER_API_KEY}
      FILE_UPLOAD_PATH: ${FILE_UPLOAD_PATH}
      MAX_FILE_UPLOAD: ${MAX_FILE_UPLOAD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE: ${JWT_EXPIRE}
      JWT_COOKIE_EXPIRE: ${JWT_COOKIE_EXPIR}
      SMTP_HOST_D: ${SMTP_HOST_D}
      SMTP_PORT_D: ${SMTP_PORT_D}
      SMTP_EMAIL_D: ${SMTP_EMAIL_D}
      SMTP_PASSWORD_D: ${SMTP_PASSWORD_D}
      SMTP_SERVICE_P: ${SMTP_SERVICE_P}
      SMTP_USER_P: ${SMTP_USER_P}
      SMTP_PASSWORD_P: ${SMTP_PASSWORD_P}
      FROM_EMAIL: ${FROM_EMAIL}
      FROM_NAME: ${FROM_NAME}
