version: '3'
services:
  client:
    image: 'diltfcfs/fcfs-client'
    mem_limit: 128m
    hostname: client
  server:
    image: 'diltfcfs/fcfs-server'
    mem_limit: 128m
    hostname: api
    environment:
      - NODE_ENV=production
      - MONGO_URI=$MONGO_URI
      - MONGO_ROOT_USERNAME=$MONGO_ROOT_USERNAME
      - MONGO_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - GEOCODER_PROVIDER=$GEOCODER_PROVIDER
      - GEO_PROVIDER_API_KEY=$GEO_PROVIDER_API_KEY
      - FILE_UPLOAD_PATH=$FILE_UPLOAD_PATH
      - MAX_FILE_UPLOAD=$MAX_FILE_UPLOAD
      - JWT_SECRET=$JWT_SECRET
      - JWT_EXPIRE=$JWT_EXPIRE
      - JWT_COOKIE_EXPIRE=$JWT_COOKIE_EXPIRE
      - SMTP_HOST_D=$SMTP_HOST_D
      - SMTP_PORT_D=$SMTP_PORT_D
      - SMTP_EMAIL_D=$SMTP_EMAIL_D
      - SMTP_PASSWORD_D=$SMTP_PASSWORD_D
      - SMTP_SERVICE_P=$SMTP_SERVICE_P
      - SMTP_USER_P=$SMTP_USER_P
      - SMTP_PASSWORD_P=$SMTP_PASSWORD_P
      - FROM_EMAIL=$FROM_EMAIL
      - FROM_NAME=$FROM_NAME
  nginx:
    image: 'diltfcfs/fcfs-nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
